import { ITypes } from './types.d';

const types = {
    SET_IS_ELECTRON: 'SET_IS_ELECTRON',
    GET_SERVICE_PORTS_PENDING: 'GET_SERVICE_PORTS_PENDING',
    GET_SERVICE_PORTS_SUCCESS: 'GET_SERVICE_PORTS_SUCCESS',
    SET_SERVICE_PORTS: 'SET_SERVICE_PORTS',
} as ITypes;

export default types;
